/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";


export function Model({ ...props }) {
    const { nodes, materials } = useGLTF("/BOOM_V2.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base.geometry}
      >         
        <meshLambertMaterial color={'#111111'} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg1.geometry}
      >
        <meshLambertMaterial color={'#111111'} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Leg2.geometry}
      >
        <meshLambertMaterial color={'#111111'} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.logo.geometry}
      >         
        <meshLambertMaterial color={'#ffffff'} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.book.geometry}
      >         
        <meshLambertMaterial color={'#444444'} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plate.geometry}
      >         
        <meshBasicMaterial color={'#111111'} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.logo001.geometry}
      >        
        <meshLambertMaterial color={'#111111'} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cape.geometry}
        material={
          materials["something-is-killing-the-children-vol-1-9781684155583_hr"]
        }
      />

    </group>
  );
}

useGLTF.preload("/BOOM.gltf");
